version: '3.7'
services:
    database:
        image: 'mysql:8.0'
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: main
        ports:
            - target: 3306
              published: 3306
              protocol: tcp
